3474. Lexicographically Smallest Generated String



You are given two strings, str1 and str2, of lengths n and m, respectively.

A string word of length n + m - 1 is defined to be generated by str1 and str2 if it satisfies the following conditions for each index 0 <= i <= n - 1:

If str1[i] == 'T', the substring of word with size m starting at index i is equal to str2, i.e., word[i..(i + m - 1)] == str2.
If str1[i] == 'F', the substring of word with size m starting at index i is not equal to str2, i.e., word[i..(i + m - 1)] != str2.
Return the lexicographically smallest possible string that can be generated by str1 and str2. If no string can be generated, return an empty string "".

 

Example 1:

Input: str1 = "TFTF", str2 = "ab"

Output: "ababa"

Explanation:

The table below represents the string "ababa"
Index	T/F	Substring of length m
0	'T'	"ab"
1	'F'	"ba"
2	'T'	"ab"
3	'F'	"ba"
The strings "ababa" and "ababb" can be generated by str1 and str2.

Return "ababa" since it is the lexicographically smaller string.

Example 2:

Input: str1 = "TFTF", str2 = "abc"

Output: ""

Explanation:

No string that satisfies the conditions can be generated.

Example 3:

Input: str1 = "F", str2 = "d"

Output: "a"

 

Constraints:

1 <= n == str1.length <= 104
1 <= m == str2.length <= 500
str1 consists only of 'T' or 'F'.
str2 consists only of lowercase English characters.





























class Solution {
public:
    string findTheString(string str1, string str2) {
        int n = str1.size();
        int m = str2.size();

        string word(n + m - 1, '?');

        for (int i = 0; i < n; i++) {
            if (str1[i] == 'T') {
                for (int j = 0; j < m; j++) {
                    if (word[i + j] == '?' || word[i + j] == str2[j]) {
                        word[i + j] = str2[j];
                    } else {
                        return "";
                    }
                }
            }
        }

        for (char &c : word) {
            if (c == '?') c = 'a';
        }

        for (int i = 0; i < n; i++) {
            if (str1[i] == 'F') {

                bool match = true;
                for (int j = 0; j < m; j++) {
                    if (word[i + j] != str2[j]) {
                        match = false;
                        break;
                    }
                }

                if (match) {
                    bool broken = false;

                    for (int j = m - 1; j >= 0; j--) {
                        int pos = i + j;

                        for (char c = 'a'; c <= 'z'; c++) {
                            if (c != word[pos]) {
                                char old = word[pos];
                                word[pos] = c;

                                bool valid = true;

                                for (int k = max(0, pos - m + 1); k <= min(pos, n - 1); k++) {
                                    if (str1[k] == 'T') {
                                        for (int x = 0; x < m; x++) {
                                            if (word[k + x] != str2[x]) {
                                                valid = false;
                                                break;
                                            }
                                        }
                                        if (!valid) break;
                                    }
                                }

                                if (valid) {
                                    broken = true;
                                    break;
                                }

                                word[pos] = old;
                            }
                        }

                        if (broken) break;
                    }

                    if (!broken) return "";
                }
            }
        }

        return word;
    }
};





















class Solution {
    vector<int> calcZ(const string &s) {
        int size = s.size();
        vector<int> z(size, 0);
        int l = 0, r = 0;   // z-box: [l, r]
        for (int i = 1; i < size; i++) {
            if (i <= r)
                z[i] = min(z[i - l], r - i + 1);
            while (i + z[i] < size && s[z[i]] == s[i + z[i]]) {
                l = i;
                r = i + z[i]++;
            }
        }
        z[0] = size;
        return z;
    }
public:
    string generateString(string str1, string str2) {
        int size1 = str1.size(), size2 = str2.size();
        int wordSize = size1 + size2 - 1;
        string word(wordSize, '*');
        vector<int> z = calcZ(str2);

        // process T
        int pre = -size2;
        for (int i = 0; i < size1; i++) {
            if (str1[i] == 'F')
                continue;
            int residueLen = max(0, pre + size2 - i);
            if (residueLen && z[size2 - residueLen] < residueLen)
                return "";
            for (int j = residueLen; j < size2; j++) {
                word[i + j] = str2[j];
            }
            pre = i;
        }

        vector<int> lastWild(wordSize, -1);
        pre = -1;
        for (int i = 0; i < wordSize; i++) {
            if (word[i] == '*') {
                word[i] = 'a';
                pre = i;
            }
            lastWild[i] = pre;
        }

        // process F
        z = calcZ(str2 + word);
        for (int i = 0; i < size1; i++) {
            if (str1[i] == 'T' || z[size2 + i] < size2)
                continue;
            int candidatePos = lastWild[i + size2 - 1];
            if (candidatePos < i)
                return "";
            word[candidatePos] = 'b';
            i = candidatePos;
        }
        return word;
    }
};




































class StringHasher {
private:
    vector<unsigned int> power, prefix;
public:
    StringHasher(const string& s, unsigned int base, int start) {
        int n = s.length();
        prefix.assign(n + 1, 0);
        power.assign(n + 1, 0);
        power[0] = 1;
        for (int i = 0; i < n; i++) {
            power[i + 1] = power[i] * base;
            prefix[i + 1] = prefix[i] * base + s[i] - start;
        }
    }
    
    unsigned int get(int l, int r) {
        return prefix[r] - prefix[l] * power[r - l];
    }
};

class Solution {
public:
    string generateString(string str1, string str2) {
        string pattern = str2;
        string s = str1;
        StringHasher hash(pattern, 29, 'a');
        
        int m = pattern.length();
        int n = s.length();
        int prev = -m;
        int prevValid = -1;
        
        vector<int> valid(n + m - 1);
        string ans(n + m - 1, ' ');
        
        for (int i = 0; i < n + m - 1; i++) {
            if (i < n && s[i] == 'T') {
                if (i - prev < m && hash.get(i - prev, m) != hash.get(0, m - i + prev)) {
                    return "";
                }
                prev = i;
            }
            
            if (i - prev < m) {
                ans[i] = pattern[i - prev];
            } else {
                prevValid = i;
                ans[i] = 'a';
            }
            valid[i] = prevValid;
        }
        
        StringHasher hash2(ans, 29, 'a');
        unsigned int val = hash.get(0, m);
        
        for (int i = m; i < n + m; i++) {
            if (s[i - m] == 'F' && hash2.get(i - m, i) == val) {
                if (valid[i - 1] < i - m) {
                    return ""; 
                }
                ans[valid[i - 1]] = 'b';
                
                i = valid[i - 1] + m;
            }
        }
        
        return ans;
    }
};






























#include <string>
#include <vector>
#include <bitset>

using namespace std;

#pragma GCC optimize("Ofast,unroll-loops")
#pragma GCC target("avx2,bmi,bmi2")

static const int fast_io = []() {
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    return 0;
}();

class Solution {
public:
    string generateString(string str1, string str2) {
        const int n = str1.length();
        const int m = str2.length();
        const int total_len = n + m - 1;
        
        string word(total_len, 'a');
        vector<bool> fixed(total_len, false);

        // 1. Отработка 'T' - это база
        for (int i = 0; i < n; ++i) {
            if (str1[i] == 'T') {
                for (int j = 0; j < m; ++j) {
                    if (fixed[i + j] && word[i + j] != str2[j]) return "";
                    word[i + j] = str2[j];
                    fixed[i + j] = true;
                }
            }
        }

        // 2. Валидация 'T' - критично для сложных наложений
        for (int i = 0; i < n; ++i) {
            if (str1[i] == 'T') {
                for (int j = 0; j < m; ++j) {
                    if (word[i + j] != str2[j]) return "";
                }
            }
        }

        // 3. Быстрая проверка 'F' через string_view или кастомный memcmp
        // Но секрет 100% в том, чтобы проверять только те окна, 
        // где ПЕРВЫЙ и ПОСЛЕДНИЙ символы совпадают с str2
        for (int i = 0; i < n; ++i) {
            if (str1[i] == 'F') {
                // Быстрый фильтр: если первый или последний символ не совпал, 
                // то и вся подстрока не совпадет.
                if (word[i] == str2[0] && word[i + m - 1] == str2[m - 1]) {
                    bool match = true;
                    // Используем встроенный высокооптимизированный компаратор
                    if (word.compare(i, m, str2) == 0) {
                        // Нашли запрещенное совпадение
                        bool changed = false;
                        for (int j = m - 1; j >= 0; --j) {
                            if (!fixed[i + j]) {
                                // Ищем минимальный символ, который не равен str2[j]
                                word[i + j] = (str2[j] == 'a' ? 'b' : 'a');
                                changed = true;
                                break;
                            }
                        }
                        if (!changed) return "";
                    }
                }
            }
        }

        return word;
    }
};















































class Solution {
public:
    string generateString(string str1, string str2) {
        int n = str1.size();
        int m = str2.size();
        int L = n + m - 1;

        string word(L, '?');
        vector<bool> locked(L, false);

        for (int i = 0; i < n; i++) {
            if (str1[i] == 'T') {
                for (int j = 0; j < m; j++) {
                    if (word[i + j] == '?' || word[i + j] == str2[j]) {
                        word[i + j] = str2[j];
                        locked[i + j] = true;
                    } else {
                        return "";
                    }
                }
            }
        }
        for (int i = 0; i < L; i++) {
            if (word[i] == '?') {
                word[i] = 'a';
            }
        }

        for (int i = 0; i < n; i++) {
            if (str1[i] == 'F') {

                bool match = true;
                for (int j = 0; j < m; j++) {
                    if (word[i + j] != str2[j]) {
                        match = false;
                        break;
                    }
                }

                if (match) {
                    bool ok = false;

                    for (int j = m - 1; j >= 0; j--) {

                        if (locked[i + j]) continue;

                        for (char c = 'a'; c <= 'z'; c++) {
                            if (c == str2[j]) continue;

                            char old = word[i + j];
                            word[i + j] = c;

                            bool stillMatch = true;
                            for (int k = 0; k < m; k++) {
                                if (word[i + k] != str2[k]) {
                                    stillMatch = false;
                                    break;
                                }
                            }

                            if (!stillMatch) {
                                ok = true;
                                break;
                            }

                            word[i + j] = old;
                        }

                        if (ok) break;
                    }

                    if (!ok) return "";
                }
            }
        }

        return word;
    }
};


































#include <string>
#include <vector>

using namespace std;

#pragma GCC optimize("Ofast")
static const int fast_io = []() {
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    return 0;
}();

class Solution {
public:
    string generateString(string str1, string str2) {
        int n = str1.length();
        int m = str2.length();
        int len = n + m - 1;
        string word(len, '?');
        vector<bool> fixed(len, false);

        // 1. Накладываем все 'T'
        for (int i = 0; i < n; ++i) {
            if (str1[i] == 'T') {
                for (int j = 0; j < m; ++j) {
                    if (word[i + j] != '?' && word[i + j] != str2[j]) return "";
                    word[i + j] = str2[j];
                    fixed[i + j] = true;
                }
            }
        }

        // 2. Проверка консистентности 'T' (на всякий случай)
        for (int i = 0; i < n; ++i) {
            if (str1[i] == 'T') {
                for (int j = 0; j < m; ++j) {
                    if (word[i + j] != str2[j]) return "";
                }
            }
        }

        // 3. Жадное заполнение неопределенных мест символом 'a'
        for (int i = 0; i < len; ++i) {
            if (word[i] == '?') word[i] = 'a';
        }

        // 4. Обработка 'F'
        // Идем слева направо. Если видим 'F', нарушающее условие, 
        // меняем самый правый свободный символ в этом окне на 'b'.
        for (int i = 0; i < n; ++i) {
            if (str1[i] == 'F') {
                bool match = true;
                for (int j = 0; j < m; ++j) {
                    if (word[i + j] != str2[j]) {
                        match = false;
                        break;
                    }
                }

                if (match) {
                    // Нужно изменить хотя бы один символ в диапазоне [i, i+m-1]
                    // который НЕ зафиксирован 'T'. Ищем с конца для минимизации.
                    bool changed = false;
                    for (int j = m - 1; j >= 0; --j) {
                        if (!fixed[i + j]) {
                            // Меняем на 'b', так как 'a' там уже была (или была частью чего-то)
                            // Если там была не 'a', а 'str2[j]', то 'a' точно меньше.
                            // Но мы заполнили свободные 'a', значит там сейчас 'a' == str2[j].
                            // Ставим 'b'.
                            word[i + j] = 'b';
                            changed = true;
                            break; 
                        }
                    }
                    if (!changed) return ""; // Все символы в окне 'F' зафиксированы 'T'
                }
            }
        }

        return word;
    }
};

































